export const tableData = {
  bigTitle: "Our Tables",
  products: [
    {
      id: 1,
      image: "/assets/images/tables/tables-one.jpeg",
      title: "Classic Wooden Table",
      description: "High-quality oak wood table with a smooth finish.",
      price: "$250",
      oldPrice: "$300",
      discount: "15%",
      isNew: true,
    },
    {
      id: 2,
      image: "/assets/images/tables/tables-two.jpeg",
      title: "Modern Glass Table",
      description: "Stylish tempered glass table with a metal frame.",
      price: "$320",
    },
    {
      id: 3,
      image: "/assets/images/tables/tables-three.jpeg",
      title: "Round Dining Table",
      description: "Elegant round dining table made of walnut wood.",
      price: "$400",
      oldPrice: "$450",
      discount: "10%",
    },
    {
      id: 4,
      image: "/assets/images/tables/tables-four.jpeg",
      title: "Folding Study Table",
      description: "Compact and foldable study table made of pine wood.",
      price: "$180",
    },
    {
      id: 5,
      image: "/assets/images/tables/tables-five.jpeg",
      title: "Metal Frame Office Table",
      description: "Durable office table with a metal frame and MDF top.",
      price: "$280",
    },
    {
      id: 6,
      image: "/assets/images/tables/tables-six.jpeg",
      title: "Rustic Farmhouse Table",
      description: "Handcrafted rustic farmhouse table made of reclaimed wood.",
      price: "$450",
      oldPrice: "$500",
      discount: "10%",
    },
    {
      id: 7,
      image: "/assets/images/tables/tables-seven.jpeg",
      title: "White Minimal Table",
      description: "Simple and modern white minimalistic table.",
      price: "$230",
    },
    {
      id: 8,
      image: "/assets/images/tables/tables-eight.jpeg",
      title: "Vintage Coffee Table",
      description: "A stylish vintage coffee table with intricate designs.",
      price: "$190",
    },
    {
      id: 9,
      image: "/assets/images/tables/tables-one.jpeg",
      title: "Adjustable Height Table",
      description: "Ergonomic height-adjustable office table.",
      price: "$350",
      oldPrice: "$400",
      discount: "12%",
    },
    {
      id: 10,
      image: "/assets/images/tables/tables-two.jpeg",
      title: "Marble Top Table",
      description: "Luxurious marble top dining table with metal legs.",
      price: "$600",
    },
    {
      id: 11,
      image: "/assets/images/tables/tables-three.jpeg",
      title: "Kids Study Table",
      description: "Colorful and functional study table for kids.",
      price: "$120",
    },
    {
      id: 12,
      image: "/assets/images/tables/tables-four.jpeg",
      title: "Portable Laptop Table",
      description: "Lightweight and foldable laptop table for easy use.",
      price: "$90",
    },
    {
      id: 13,
      image: "/assets/images/tables/tables-five.jpeg",
      title: "Industrial Work Table",
      description: "Heavy-duty industrial work table with steel frame.",
      price: "$500",
      oldPrice: "$550",
      discount: "9%",
    },
    {
      id: 14,
      image: "/assets/images/tables/tables-six.jpeg",
      title: "Teakwood Dining Table",
      description: "Elegant dining table made of premium teakwood.",
      price: "$700",
    },
    {
      id: 15,
      image: "/assets/images/tables/tables-seven.jpeg",
      title: "Convertible Desk Table",
      description:
        "Space-saving convertible desk that transforms into a shelf.",
      price: "$400",
      oldPrice: "$450",
      discount: "11%",
    },
    {
      id: 16,
      image: "/assets/images/tables/tables-eight.jpeg",
      title: "Glass Coffee Table",
      description: "Modern glass coffee table with wooden legs.",
      price: "$270",
    },
  ],
};
