export const officeData = {
  bigTitle: "Office Collection",
  products: [
    {
      id: 1,
      image: "/assets/images/office/office-one.jpeg",
      title: "Ergonomic Office Chair",
      description: "Comfortable ergonomic chair for long working hours.",
      price: "$450",
      oldPrice: "$500",
      discount: "10%",
      isNew: true,
    },
    {
      id: 2,
      image: "/assets/images/office/office-two.jpeg",
      title: "Modern Office Desk",
      description: "Spacious office desk with sleek design.",
      price: "$800",
    },
    {
      id: 3,
      image: "/assets/images/office/office-three.jpeg",
      title: "Bookshelf with Storage",
      description: "Stylish bookshelf with multiple compartments.",
      price: "$600",
      oldPrice: "$700",
      discount: "14%",
    },
    {
      id: 4,
      image: "/assets/images/office/office-four.jpeg",
      title: "Adjustable Standing Desk",
      description: "Height-adjustable desk for a comfortable workspace.",
      price: "$1200",
    },
    {
      id: 5,
      image: "/assets/images/office/office-five.jpeg",
      title: "Filing Cabinet",
      description: "Secure and spacious filing cabinet for documents.",
      price: "$500",
    },
    {
      id: 6,
      image: "/assets/images/office/office-six.jpeg",
      title: "LED Desk Lamp",
      description: "Energy-efficient LED desk lamp with adjustable brightness.",
      price: "$100",
      oldPrice: "$120",
      discount: "17%",
    },
    {
      id: 7,
      image: "/assets/images/office/office-seven.jpeg",
      title: "Minimalist Office Table",
      description: "Sleek and functional office table for workstations.",
      price: "$750",
    },
    {
      id: 8,
      image: "/assets/images/office/office-eight.jpeg",
      title: "Executive Office Chair",
      description: "Luxury office chair with high-back support.",
      price: "$900",
    },
    {
      id: 9,
      image: "/assets/images/office/office-one.jpeg",
      title: "Multipurpose Workstation",
      description: "All-in-one workstation with ample storage.",
      price: "$1500",
      oldPrice: "$1700",
      discount: "12%",
    },
    {
      id: 10,
      image: "/assets/images/office/office-two.jpeg",
      title: "Compact Office Desk",
      description: "Space-saving office desk for small spaces.",
      price: "$650",
    },
    {
      id: 11,
      image: "/assets/images/office/office-three.jpeg",
      title: "Whiteboard with Stand",
      description: "Portable whiteboard for meetings and brainstorming.",
      price: "$300",
    },
    {
      id: 12,
      image: "/assets/images/office/office-four.jpeg",
      title: "Storage Credenza",
      description: "Modern credenza for office storage and decor.",
      price: "$850",
    },
    {
      id: 13,
      image: "/assets/images/office/office-five.jpeg",
      title: "Ergonomic Footrest",
      description: "Adjustable footrest for better posture support.",
      price: "$80",
      oldPrice: "$100",
      discount: "20%",
    },
    {
      id: 14,
      image: "/assets/images/office/office-six.jpeg",
      title: "Conference Table",
      description: "Spacious conference table for meetings.",
      price: "$2000",
    },
    {
      id: 15,
      image: "/assets/images/office/office-seven.jpeg",
      title: "Under-Desk Drawer Unit",
      description: "Compact drawer unit for office supplies.",
      price: "$280",
      oldPrice: "$320",
      discount: "13%",
    },
    {
      id: 16,
      image: "/assets/images/office/office-eight.jpeg",
      title: "Acoustic Office Panels",
      description: "Sound-absorbing panels for a quieter workspace.",
      price: "$500",
    },
  ],
};
