export const bedroomData = {
  bigTitle: "Bedroom Collection",
  products: [
    {
      id: 1,
      image: "/assets/images/bedroom/bedroom-one.jpeg",
      title: "Luxury King Bed",
      description: "Elegant king-size bed with premium comfort.",
      price: "$2500",
      oldPrice: "$2800",
      discount: "11%",
      isNew: true,
    },
    {
      id: 2,
      image: "/assets/images/bedroom/bedroom-two.jpeg",
      title: "Modern Nightstand",
      description: "Minimalist nightstand with storage drawers.",
      price: "$320",
    },
    {
      id: 3,
      image: "/assets/images/bedroom/bedroom-three.jpeg",
      title: "Spacious Wardrobe",
      description: "Stylish wardrobe with ample storage capacity.",
      price: "$1800",
      oldPrice: "$2000",
      discount: "10%",
    },
    {
      id: 4,
      image: "/assets/images/bedroom/bedroom-four.jpeg",
      title: "Comfortable Mattress",
      description: "Premium quality mattress for restful sleep.",
      price: "$900",
    },
    {
      id: 5,
      image: "/assets/images/bedroom/bedroom-five.jpeg",
      title: "Wooden Dresser",
      description: "Classic wooden dresser with multiple drawers.",
      price: "$750",
    },
    {
      id: 6,
      image: "/assets/images/bedroom/bedroom-six.jpeg",
      title: "Soft Bedside Lamp",
      description: "Warm and cozy bedside lamp for night reading.",
      price: "$150",
      oldPrice: "$180",
      discount: "17%",
    },
    {
      id: 7,
      image: "/assets/images/bedroom/bedroom-seven.jpeg",
      title: "Minimalist Vanity Table",
      description: "Stylish vanity table with mirror and drawers.",
      price: "$680",
    },
    {
      id: 8,
      image: "/assets/images/bedroom/bedroom-eight.jpeg",
      title: "Elegant Bedding Set",
      description: "Soft and comfortable bedding set with pillows.",
      price: "$350",
    },
    {
      id: 9,
      image: "/assets/images/bedroom/bedroom-one.jpeg",
      title: "Convertible Sofa Bed",
      description: "Space-saving sofa that turns into a bed.",
      price: "$1200",
      oldPrice: "$1400",
      discount: "14%",
    },
    {
      id: 10,
      image: "/assets/images/bedroom/bedroom-two.jpeg",
      title: "Scandinavian Bed Frame",
      description: "Minimalist wooden bed frame with sturdy support.",
      price: "$1100",
    },
    {
      id: 11,
      image: "/assets/images/bedroom/bedroom-three.jpeg",
      title: "Tufted Headboard",
      description: "Elegant tufted headboard for a luxurious look.",
      price: "$550",
    },
    {
      id: 12,
      image: "/assets/images/bedroom/bedroom-four.jpeg",
      title: "Compact Storage Bench",
      description: "Perfect storage bench for extra bedroom space.",
      price: "$280",
    },
    {
      id: 13,
      image: "/assets/images/bedroom/bedroom-five.jpeg",
      title: "Rustic Wooden Nightstand",
      description: "Handcrafted wooden nightstand with storage.",
      price: "$450",
      oldPrice: "$500",
      discount: "10%",
    },
    {
      id: 14,
      image: "/assets/images/bedroom/bedroom-six.jpeg",
      title: "Handcrafted Bed Frame",
      description: "Solid wood bed frame with a natural finish.",
      price: "$1400",
    },
    {
      id: 15,
      image: "/assets/images/bedroom/bedroom-seven.jpeg",
      title: "Foldable Storage Ottoman",
      description: "Multipurpose ottoman with hidden storage.",
      price: "$320",
      oldPrice: "$380",
      discount: "16%",
    },
    {
      id: 16,
      image: "/assets/images/bedroom/bedroom-eight.jpeg",
      title: "Bohemian Style Blanket",
      description: "Cozy bohemian-style blanket with soft texture.",
      price: "$180",
    },
  ],
};
