export const chairData = {
  bigTitle: "Our Chairs",
  products: [
    {
      id: 1,
      image: "/assets/images/chairs/chair-one.jpeg",
      title: "Classic Leather Chair",
      description: "Premium quality leather chair with a modern touch.",
      price: "$250",
      oldPrice: "$300",
      discount: "17%",
      isNew: true,
    },
    {
      id: 2,
      image: "/assets/images/chairs/chair-two.jpeg",
      title: "Modern Fabric Chair",
      description: "Comfortable fabric chair with a stylish design.",
      price: "$180",
    },
    {
      id: 3,
      image: "/assets/images/chairs/chair-three.jpeg",
      title: "Ergonomic Office Chair",
      description: "Adjustable ergonomic chair for maximum comfort.",
      price: "$320",
      oldPrice: "$350",
      discount: "9%",
    },
    {
      id: 4,
      image: "/assets/images/chairs/chair-four.jpeg",
      title: "Recliner Chair",
      description: "Luxury recliner chair with adjustable positions.",
      price: "$450",
    },
    {
      id: 5,
      image: "/assets/images/chairs/chair-five.jpeg",
      title: "Velvet Armchair",
      description: "Elegant velvet armchair with deep cushioning.",
      price: "$380",
    },
    {
      id: 6,
      image: "/assets/images/chairs/chair-six.jpeg",
      title: "Minimalist Grey Chair",
      description: "A simple yet modern grey fabric chair.",
      price: "$210",
      oldPrice: "$250",
      discount: "16%",
    },
    {
      id: 7,
      image: "/assets/images/chairs/chair-seven.jpeg",
      title: "Wooden Frame Chair",
      description: "Rustic wooden frame chair with soft cushions.",
      price: "$270",
    },
    {
      id: 8,
      image: "/assets/images/chairs/chair-eight.jpeg",
      title: "Luxury Lounge Chair",
      description: "High-end lounge chair with premium cushioning.",
      price: "$700",
    },
    {
      id: 9,
      image: "/assets/images/chairs/chair-one.jpeg",
      title: "Convertible Chair Bed",
      description: "Space-saving chair that transforms into a bed.",
      price: "$340",
      oldPrice: "$400",
      discount: "15%",
    },
    {
      id: 10,
      image: "/assets/images/chairs/chair-two.jpeg",
      title: "Scandinavian Chair",
      description: "Minimalist Scandinavian-style wooden chair.",
      price: "$230",
    },
    {
      id: 11,
      image: "/assets/images/chairs/chair-three.jpeg",
      title: "Tufted Velvet Chair",
      description: "Luxurious tufted velvet chair with gold legs.",
      price: "$410",
    },
    {
      id: 12,
      image: "/assets/images/chairs/chair-four.jpeg",
      title: "Compact Dining Chair",
      description: "Perfectly designed compact chair for small spaces.",
      price: "$160",
    },
    {
      id: 13,
      image: "/assets/images/chairs/chair-five.jpeg",
      title: "Industrial Leather Chair",
      description: "Vintage-style industrial leather chair.",
      price: "$480",
      oldPrice: "$530",
      discount: "9%",
    },
    {
      id: 14,
      image: "/assets/images/chairs/chair-six.jpeg",
      title: "Handcrafted Wooden Chair",
      description: "Handmade wooden chair with durable fabric.",
      price: "$320",
    },
    {
      id: 15,
      image: "/assets/images/chairs/chair-seven.jpeg",
      title: "Folding Lounge Chair",
      description: "Foldable lounge chair for easy storage.",
      price: "$260",
      oldPrice: "$300",
      discount: "13%",
    },
    {
      id: 16,
      image: "/assets/images/chairs/chair-eight.jpeg",
      title: "Bohemian Style Chair",
      description: "Cozy bohemian-style chair with colorful patterns.",
      price: "$280",
    },
  ],
};
