export const livingRoomData = {
  bigTitle: "Living Room Collection",
  products: [
    {
      id: 1,
      image: "/assets/images/living-room/living-room-one.jpeg",
      title: "Modern Sofa Set",
      description: "Luxurious modern sofa set for a stylish living room.",
      price: "$2200",
      oldPrice: "$2500",
      discount: "12%",
      isNew: true,
    },
    {
      id: 2,
      image: "/assets/images/living-room/living-room-two.jpeg",
      title: "Contemporary Coffee Table",
      description: "Sleek coffee table with a minimalistic design.",
      price: "$450",
    },
    {
      id: 3,
      image: "/assets/images/living-room/living-room-three.jpeg",
      title: "Elegant TV Stand",
      description: "Spacious and stylish TV stand with storage.",
      price: "$600",
      oldPrice: "$700",
      discount: "14%",
    },
    {
      id: 4,
      image: "/assets/images/living-room/living-room-four.jpeg",
      title: "Recliner Lounge Chair",
      description: "Comfortable recliner chair for relaxation.",
      price: "$750",
    },
    {
      id: 5,
      image: "/assets/images/living-room/living-room-five.jpeg",
      title: "Wooden Bookshelf",
      description: "Handcrafted wooden bookshelf for storage and decor.",
      price: "$900",
    },
    {
      id: 6,
      image: "/assets/images/living-room/living-room-six.jpeg",
      title: "Minimalist Floor Lamp",
      description: "Modern floor lamp for a cozy ambiance.",
      price: "$200",
      oldPrice: "$250",
      discount: "20%",
    },
    {
      id: 7,
      image: "/assets/images/living-room/living-room-seven.jpeg",
      title: "Rustic Coffee Table Set",
      description: "A set of two rustic wooden coffee tables.",
      price: "$580",
    },
    {
      id: 8,
      image: "/assets/images/living-room/living-room-eight.jpeg",
      title: "Luxury Sectional Sofa",
      description: "Premium sectional sofa for maximum comfort.",
      price: "$3200",
    },
    {
      id: 9,
      image: "/assets/images/living-room/living-room-one.jpeg",
      title: "Convertible Sofa Bed",
      description: "Space-saving sofa that transforms into a bed.",
      price: "$1400",
      oldPrice: "$1600",
      discount: "13%",
    },
    {
      id: 10,
      image: "/assets/images/living-room/living-room-two.jpeg",
      title: "Scandinavian Armchair",
      description: "Minimalist Scandinavian-style fabric armchair.",
      price: "$450",
    },
    {
      id: 11,
      image: "/assets/images/living-room/living-room-three.jpeg",
      title: "Velvet Accent Chair",
      description: "Luxurious velvet accent chair with gold legs.",
      price: "$650",
    },
    {
      id: 12,
      image: "/assets/images/living-room/living-room-four.jpeg",
      title: "Compact Side Table",
      description: "Perfectly designed side table for small spaces.",
      price: "$180",
    },
    {
      id: 13,
      image: "/assets/images/living-room/living-room-five.jpeg",
      title: "Vintage Wooden Cabinet",
      description: "Industrial-style wooden storage cabinet.",
      price: "$1100",
      oldPrice: "$1250",
      discount: "12%",
    },
    {
      id: 14,
      image: "/assets/images/living-room/living-room-six.jpeg",
      title: "Handcrafted Coffee Table",
      description: "Handmade wooden coffee table with a modern look.",
      price: "$500",
    },
    {
      id: 15,
      image: "/assets/images/living-room/living-room-seven.jpeg",
      title: "Foldable Lounge Chair",
      description: "Stylish and foldable lounge chair for easy storage.",
      price: "$350",
      oldPrice: "$400",
      discount: "13%",
    },
    {
      id: 16,
      image: "/assets/images/living-room/living-room-eight.jpeg",
      title: "Bohemian Style Rug",
      description: "Cozy bohemian-style rug with colorful patterns.",
      price: "$320",
    },
  ],
};
