export const productData = {
  bigTitle: "Our Products",
  products: [
    {
      id: 1,
      image: "/assets/images/product-list-image/productsOne.png",
      title: "Syltherine",
      description: "Stylish cafe chair",
      price: 2500000,
      oldPrice: 3500000,
      discount: "30%",
    },
    {
      id: 2,
      image: "/assets/images/product-list-image/productsTwo.png",
      title: "Leviosa",
      description: "Stylish cafe chair", // ✅ "cofe" → "cafe"
      price: 2500000,
      isNew: false, // ✅ Qo‘shildi
    },
    {
      id: 3,
      image: "/assets/images/product-list-image/productsThree.png",
      title: "Lolito",
      description: "Luxury big sofa",
      price: 7000000,
      oldPrice: 14000000,
      discount: "50%",
    },
    {
      id: 4,
      image: "/assets/images/product-list-image/productsFour.png",
      title: "Respira",
      description: "Minimalist fan",
      price: 500000,
      isNew: true,
    },
    {
      id: 5,
      image: "/assets/images/product-list-image/productsFive.png",
      title: "Grifo",
      description: "Night lamp",
      price: 7000000,
    },
    {
      id: 6,
      image: "/assets/images/product-list-image/productsSix.png",
      title: "Muggo",
      description: "Small mug",
      price: 150000,
      isNew: true,
    },
    {
      id: 7,
      image: "/assets/images/product-list-image/productsSeven.png",
      title: "Muggo",
      description: "Small mug",
      price: 150000,
      isNew: true,
    },
    {
      id: 8,
      image: "/assets/images/product-list-image/productsEight.png",
      title: "Pingky",
      description: "Cute bed set",
      price: 7000000,
      oldPrice: 14000000,
      discount: "50%",
    },
    {
      id: 9,
      image: "/assets/images/product-list-image/productsOne.png",
      title: "Syltherine",
      description: "Stylish cafe chair",
      price: 2500000,
      oldPrice: 3500000,
      discount: "30%",
    },
    {
      id: 10,
      image: "/assets/images/product-list-image/productsTwo.png",
      title: "Leviosa",
      description: "Stylish cafe chair", // ✅ "cofe" → "cafe"
      price: 2500000,
      isNew: false, // ✅ Qo‘shildi
    },
    {
      id: 11,
      image: "/assets/images/product-list-image/productsThree.png",
      title: "Lolito",
      description: "Luxury big sofa",
      price: 7000000,
      oldPrice: 14000000,
      discount: "50%",
    },
    {
      id: 12,
      image: "/assets/images/product-list-image/productsFour.png",
      title: "Respira",
      description: "Minimalist fan",
      price: 500000,
      isNew: true,
    },
    {
      id: 13,
      image: "/assets/images/product-list-image/productsFive.png",
      title: "Grifo",
      description: "Night lamp",
      price: 7000000,
    },
    {
      id: 14,
      image: "/assets/images/product-list-image/productsSix.png",
      title: "Muggo",
      description: "Small mug",
      price: 150000,
      isNew: true,
    },
    {
      id: 15,
      image: "/assets/images/product-list-image/productsSeven.png",
      title: "Muggo",
      description: "Small mug",
      price: 150000,
      isNew: true,
    },
    {
      id: 16,
      image: "/assets/images/product-list-image/productsEight.png",
      title: "Pingky",
      description: "Cute bed set",
      price: 7000000,
      oldPrice: 14000000,
      discount: "50%",
    },
  ],
};
