export const sofaData = {
  bigTitle: "Our Sofas",
  products: [
    {
      id: 1,
      image: "/assets/images/sofas/sofa-one.jpeg",
      title: "Classic Leather Sofa",
      description: "Premium quality leather sofa with a modern touch.",
      price: "$1200",
      oldPrice: "$1500",
      discount: "20%",
      isNew: true,
    },
    {
      id: 2,
      image: "/assets/images/sofas/sofa-two.jpeg",
      title: "Modern Fabric Sofa",
      description: "Comfortable fabric sofa with a stylish design.",
      price: "$950",
    },
    {
      id: 3,
      image: "/assets/images/sofas/sofa-three.jpeg",
      title: "L-Shaped Corner Sofa",
      description: "Spacious L-shaped corner sofa for maximum comfort.",
      price: "$1800",
      oldPrice: "$2000",
      discount: "10%",
    },
    {
      id: 4,
      image: "/assets/images/sofas/sofa-four.jpeg",
      title: "Recliner Sofa",
      description: "Luxury recliner sofa with adjustable positions.",
      price: "$1400",
    },
    {
      id: 5,
      image: "/assets/images/sofas/sofa-five.jpeg",
      title: "Velvet Chesterfield Sofa",
      description: "Elegant velvet Chesterfield sofa with deep buttoning.",
      price: "$1600",
    },
    {
      id: 6,
      image: "/assets/images/sofas/sofa-six.jpeg",
      title: "Minimalist Grey Sofa",
      description: "A simple yet modern grey fabric sofa.",
      price: "$1000",
      oldPrice: "$1200",
      discount: "16%",
    },
    {
      id: 7,
      image: "/assets/images/sofas/sofa-seven.jpeg",
      title: "Wooden Frame Sofa",
      description: "Rustic wooden frame sofa with soft cushions.",
      price: "$1300",
    },
    {
      id: 8,
      image: "/assets/images/sofas/sofa-eight.jpeg",
      title: "Luxury Sectional Sofa",
      description: "High-end sectional sofa with premium cushioning.",
      price: "$2500",
    },
    {
      id: 9,
      image: "/assets/images/sofas/sofa-one.jpeg",
      title: "Convertible Sofa Bed",
      description: "Space-saving sofa that transforms into a bed.",
      price: "$1100",
      oldPrice: "$1300",
      discount: "15%",
    },
    {
      id: 10,
      image: "/assets/images/sofas/sofa-two.jpeg",
      title: "Scandinavian Sofa",
      description: "Minimalist Scandinavian-style fabric sofa.",
      price: "$900",
    },
    {
      id: 11,
      image: "/assets/images/sofas/sofa-three.jpeg",
      title: "Tufted Velvet Sofa",
      description: "Luxurious tufted velvet sofa with gold legs.",
      price: "$1700",
    },
    {
      id: 12,
      image: "/assets/images/sofas/sofa-four.jpeg",
      title: "Compact Apartment Sofa",
      description: "Perfectly designed compact sofa for small spaces.",
      price: "$850",
    },
    {
      id: 13,
      image: "/assets/images/sofas/sofa-five.jpeg",
      title: "Industrial Leather Sofa",
      description: "Vintage-style industrial leather sofa.",
      price: "$1900",
      oldPrice: "$2100",
      discount: "9%",
    },
    {
      id: 14,
      image: "/assets/images/sofas/sofa-six.jpeg",
      title: "Handcrafted Wooden Sofa",
      description: "Handmade wooden sofa with durable fabric.",
      price: "$1450",
    },
    {
      id: 15,
      image: "/assets/images/sofas/sofa-seven.jpeg",
      title: "Futon Sleeper Sofa",
      description: "Convertible futon sleeper sofa for extra functionality.",
      price: "$950",
      oldPrice: "$1100",
      discount: "13%",
    },
    {
      id: 16,
      image: "/assets/images/sofas/sofa-eight.jpeg",
      title: "Bohemian Style Sofa",
      description: "Cozy bohemian-style sofa with colorful patterns.",
      price: "$1200",
    },
  ],
};
